### ISSUE TITLE
paddle2onnx, sync_batch_norm不支持

### ISSUE THREAD

**Issue by rourou8023** [PaddlePaddle/Paddle2ONNX#319] opened 2021-09-09 07:21 UTC
paddle模型转onnx，报下面的错：
There's 1 ops are not supported yet
=========== sync_batch_norm ===========
应该怎么解决呢？

**Comment by jiangjiajun** [comment] 2021-09-09 10:41
你好，sync_batch_norm不属于应该正常导出来的OP，请联系源REPO，反馈此问题

**Comment by jiangjiajun** [comment] 2021-09-14 03:35
Duplicate of https://github.com/PaddlePaddle/PaddleSeg/issues/1335

**Closed as completed** 2024-05-22 03:48 UTC
