### ISSUE TITLE
paddle2onnx,使用onnxruntime-gpu验证转换的onnx与paddle模型的预测结果时，显示bad

### ISSUE THREAD

**Issue by rourou8023** [PaddlePaddle/Paddle2ONNX#322] opened 2021-09-13 03:58 UTC
1）paddleseg保存的OCRnet模型，使用paddle2onnx将paddle动态图模型转换为onnx模型；
2）针对同一个输入，使用onnxruntime-gpu推理onnx模型推理结果与paddle结果差别很大；
3）但是使用onnxruntime-cpu推理onnx模型，与paddle的结果很相近。
麻烦问下可能是什么原因导致的呢？

paddlepaddle-GPU： 2.1.2
CUDA: 10.1
cuDNN: 7.6.5
onnxruntime: 1.4.0

推理结果对比：
cpu:
Exported model has been predicted by ONNXRuntime!
ONNXRuntime predict time: 5.0517 s
Paddle predict time: 0.8682 s
The difference of results between ONNXRuntime and Paddle looks good!
relative_diff: 1.0463244e-06
max_abs_diff: 1.1444092e-05

gpu:
Exported model has been predicted by ONNXRuntime!
ONNXRuntime predict time: 1.0025 s
Paddle predict time: 0.9931 s
The difference of results between ONNXRuntime and Paddle looks bad!
relative_diff: 0.29378724
max_abs_diff: 3.240285

**Comment by jiangjiajun** [comment] 2021-09-13 04:09
Duplicate of #321

**Closed as completed** 2024-05-22 05:09 UTC
Labels: Bug, ONNXRuntime(Version)
