### ISSUE TITLE
Can't convert PGNet model to Openvino

### ISSUE THREAD

**Issue by tampe125** [PaddlePaddle/Paddle2ONNX#388] opened 2021-11-03 08:01 UTC
Cross-posted from https://github.com/PaddlePaddle/PaddleOCR/issues/4533

I'm having some troubles trying to convert the PGNet model into OpenVino.  
First I convert the model to ONNX using this command (original model can be found in the docs here: https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.3/doc/doc_en/pgnet_en.md#Quick_Use)

```
paddle2onnx --model_dir e2e_server_pgnetA_infer --model_filename inference.pdmodel --params_filename inference.pdiparams --save_file pgnet.onnx --opset_version 12
```
Which successfully complete.  
Then I try to convert it to OpenVino using this command:

```
python mo.py --input_model path/to/pgnet.onnx --output_dir "my/output/dir/openvino" --input_shape [1,3,480,160]
```

The shape is one that will match my images in production.  
Sadly I'm getting this error:

```
[ ERROR ]  Shape [  1 256  -1  -1] is not fully defined for output 0 of "Add_21". Use --input_shape with positive integers to override model input shapes.
[ ERROR ]  Cannot infer shapes or values for node "Add_21".
[ ERROR ]  Not all output shapes were inferred or fully defined for node "Add_21".
```

Any suggestions?

**Comment by jiangjiajun** [comment] 2021-11-03 09:39
Hi, @tampe125 

I have reproduced your problem, but this problem is caused by your defined `input_shape`.

For PGNet, the height and width have to be times of 64, e.g [1, 3, 640, 640], [1, 3, 320, 320]. (I also tried the PaddleOCR/python tools/infer/predict_e2e.py , the input shape is [1, 3, 768, 1024])

So after I modify the input shape, this model can be successfully exported to OpenVINO

```
# uninstall paddle2onnx
pip uninstall paddle2onnx
git clone https://github.com/PaddlePaddle/Paddle2ONNX.git
cd Paddle2ONNX
git checkout release/0.9
python setup.py install
``` 

use following code convert model to onnx format with fixed input shape
```
import paddle2onnx
import paddle

model_prefix = "pgnet/inference
paddle.jit.load(model_prefix)
input_shape_dict = {'x': [1, 3, 768, 1024]}
onnx_model = paddle2onnx.run_convert(model, input_shape_dict=input_shape_dict, opset_version=12)

with open("pgnet.onnx", "wb") as f:
    f.write(onnx_model.SerializeToString())
```

use following command convert onnx model to openvino ir
```
mo.py --framework onnx --input_model ocr.onnx --output_dir ov_model
```

**Comment by tampe125** [comment] 2021-11-03 09:51
Awesome! I'll give it a try later and get back to you

**Comment by tampe125** [comment] 2021-11-03 10:25
I can confirm you that everything converted without issues. One last question (if possible): do you have any example code on how to handle the output from OpenVino? I already did it for image classification, but this is a completely different application.

**Comment by jiangjiajun** [comment] 2021-11-03 10:35
https://github.com/PaddlePaddle/Paddle2ONNX/blob/release/0.9/experimental/openvino_ppdet/yolov3_infer.py

 Here is an example shows how to inference YOLOv3 by OpenVINO

You can refer the postprocess function for more details

**Closed as completed** 2024-07-15 03:46 UTC
Labels: Bug
